### ISSUE TITLE
3. Polars Expressions

### ISSUE THREAD

**Issue by SuperSupeng** [pola-rs/polars-book-cn#5]
https://pola-rs.github.io/polars-book/user-guide/dsl/intro.html

**Comment by wangzhe3224** [comment]
I will take it. But this one probably takes longer time to finish.

**Comment by linjing-lab** [comment]
You can take it, however, you need to pay attention to synchronizing the contents of the original repository to avoid the conflict of `merge & pull request`.

**Comment by linjing-lab** [comment]
use `git fetch upstream` to get the latest repository.

**Comment by linjing-lab** [comment]
> I will take it. But this one probably takes more time to finish.

Maybe you can translate some files in the `dsl` folder to reduce your burden, not all the files.

**Comment by SuperSupeng** [comment]
Yeah, It's better to separate this issue into some subtasks, like #2 .

> > I will take it. But this one probably takes more time to finish.
> 
> Maybe you can translate some files in the `dsl` folder to reduce your burden, not all the files.

**Comment by wangzhe3224** [comment]
> Yeah, It's better to separate this issue into some subtasks, like #2 .
> 
> > > I will take it. But this one probably takes more time to finish.
> > 
> > 
> > Maybe you can translate some files in the `dsl` folder to reduce your burden, not all the files.

I see. I will start from `dsl` folder then.

**Comment by SuperSupeng** [comment]
@wangzhe3224 Hi, have all the documents been translated?

**Comment by wangzhe3224** [comment]
> @wangzhe3224 Hi, have all the documents been translated?

Indeed it is!

**Comment by SuperSupeng** [comment]
> > @wangzhe3224 Hi, have all the documents been translated?
> 
> Indeed it is!

Thank you very much!
